### ISSUE TITLE
handle container restart scenario 

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-watch#10]
in testing watch, we need a means to cause Postgres to not start up, this is a different test than just killing the primary pod to cause the failover.

in this scenario, watch will detect it can't reach postgres even if Kube restarts the pod over and over.

**Comment by davecramer** [comment]
Note to self: create a C function to delete files from data dir and segfault

**Comment by jmccormick2001** [comment]
this is a general use case for when the container dies for whatever reason, Kube will restart the pod which will cause crunchy-watch issues in some cases...simulate this with execing into the container, issue a sigterm to kill postgres, as opposed to just deleting the entire pod.  Look at the informer API for a means of asyncrhously watching for these container events.  Might be a configuration option to implement this watch algorithm, the initial impl might just be "for any container failure, assume a failover is necessary".

**Comment by jmccormick2001** [comment]
use case for this also covers a data corruption which would cause pg to not stay up in the container.

**Comment by davecramer** [comment]
see #36
