### ISSUE TITLE
add DEBUG env var

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-watch#13]
setting an env var named DEBUG should cause log.Debug messages to be produced in the container log.

**Comment by abrightwell** [comment]
I'd suggest that it be called `CRUNCHY_WATCH_DEBUG` to follow the convention as well as binding it to a `--debug` flag.

**Comment by jmccormick2001** [comment]
In this particular case I would like it to be consistent with the other
containers, at least the end var.

**Comment by abrightwell** [comment]
I see it as a difference of 'how' vs. 'what' is configured.  How it is configured doesn't make any difference, in my opinion. But what is configured is the important piece.

For instance, I see no reason why any of the following wouldn't be acceptable when configured to work with or in an environment that uses `$DEBUG`:

* `export CRUNCHY_WATCH_DEBUG=$DEBUG`
* `crunchy-watch <platform> --debug=$DEBUG`
* "env": [{
       "name": "CRUNCHY_WATCH_DEBUG",
       "value": "$DEBUG"
}]

However, what if a user ONLY wants to debug `crunchy-watch`? Or what if they don't want to debug it along with everything else that may be in their environment?

I see it as a granularity that allows flexibility for end users while not prohibiting the implementation of or locking them into a more general use case.
