### ISSUE TITLE
default namespace is not a valid default namespace

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-watch#14]
currently if you do not specify a valid namespace or a namespace env var at all, watch
will default to using the 'default' NAMESPACE which is not what we want.

instead, watch should check for the NAMESPACE to be set, if not, it should produce an error message in the log and abort.

func (h failoverHandler) SetFlags(f *flag.FlagSet) {
        flags.String(f, KubeNamespace, "default")

**Comment by abrightwell** [comment]
I thought `default` was invalid only with OpenShift, is this true with Kubernetes as well?

**Comment by jmccormick2001** [comment]
The same issues arise.  'valid' is better worded as 'bad practice' I think
here.  All examples use a 'demo' namespace going forward.

**Comment by jmccormick2001** [comment]
docs updated to reflect how a namespace is set and created and used in the examples.
