### ISSUE TITLE
delete primary pod by label

### ISSUE THREAD

**Issue by mb1986** [CrunchyData/crunchy-watch#15]
Hi, thanks for very useful containers. Unfortunately I have a problem with deletion of pod which is _primary_ and **crunchy-watch** would like to exchange it. First step is to delete old primary pod and this part does not work ending with: `Error from server: pods "name=postgresql-primary" not found`.

I found code responsible for that: https://github.com/CrunchyData/crunchy-watch/blob/703256efd079315f9aff29de6687aaae8c97daa6/plugins/openshift/main.go#L93

When I test it from cli: `oc delete pod "name=postgres-primary"` it didn't work either.
The remedy for this issue is to add `-l` flag which allows pod deletion by label, e.g., `oc delete pod -l "name=postgres-primary"`.

**Comment by davecramer** [comment]
ah, good catch, although we will be moving to using the api shortly https://github.com/CrunchyData/crunchy-watch/pull/7

**Comment by mb1986** [comment]
Thx for the quick reply. Do you plan to do the same for **OpenShift** (I can see changes related only to Kubernetes)?

**Comment by davecramer** [comment]
Yes, that is in the works!

**Comment by mb1986** [comment]
I have just made a pull request adding `-l` flag to the delete command. It could fix the issue until you use api.

**Comment by jmccormick2001** [comment]
api fix merged in, should resolve this issue.
