### ISSUE TITLE
evaluate desescalation of privs on openshift

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-watch#50]
evaluate ocp privs and what is the minimal reqts, where possible deescalate so that cluster role is not required to run watch.

**Comment by abrightwell** [comment]
Perhaps creating a local custom role would be an appropriate option? It obviously wouldn't be a cluster role, but I'm not convinced that would be a bad thing.

https://docs.openshift.com/container-platform/3.9/admin_guide/manage_rbac.html#creating-local-role
https://docs.openshift.com/container-platform/3.9/architecture/additional_concepts/authorization.html#evaluating-authorization

Maybe something like:

```
$> oc create role crunchy-watch-role --verb=get --verb=list --verb=delete --resource=pods
$> oc policy add-role-to-user crunchy-watch-role system:serviceaccount:<project_name>:pg-watcher
```
Is somewhat along the lines of what you were thinking?

**Comment by jmccormick2001** [comment]
I've recently changed the operator rbac rules to not use cluster role, you might borrow from the example here:

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgo-role
  namespace: $CO_NAMESPACE
rules:
- apiGroups:
  - '*'
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgo-role-binding
  namespace: $CO_NAMESPACE
subjects:
- kind: ServiceAccount
  name: postgres-operator
  namespace: $CO_NAMESPACE
roleRef:
  kind: Role
  name: pgo-role
  apiGroup: rbac.authorization.k8s.io

**Comment by jmccormick2001** [comment]
merged in refactored rbac rules for this into develop branch.
