### ISSUE TITLE
Crunchy-watch : Failover not happening.

### ISSUE THREAD

**Issue by uhaani** [CrunchyData/crunchy-watch#70]
below are the logs when primary is deleted - 
Starting crunchy watch
Started...
INFO[2018-10-22T15:44:54Z] Loading Platform Module: kube
INFO[2018-10-22T15:44:54Z] Waiting for signal...
INFO[2018-10-22T15:44:54Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:44:54Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:04Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:04Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:14Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:14Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:24Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:24Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:34Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:34Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:44Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:44Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:45:54Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:45:54Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:46:04Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:46:04Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:46:14Z] Health Checking: 'crunchy-primary'
INFO[2018-10-22T15:46:14Z] Successfully reached 'crunchy-primary'
INFO[2018-10-22T15:46:24Z] Health Checking: 'crunchy-primary'
ERRO[2018-10-22T15:46:34Z] dial tcp 10.105.143.178:5432: i/o timeout
ERRO[2018-10-22T15:46:34Z] Could not reach 'crunchy-primary' (Attempt: 1)
INFO[2018-10-22T15:46:34Z] Executing pre-hook: /hooks/watch-pre-hook
INFO[2018-10-22T15:46:34Z] Processing Failover: Strategy - latest
INFO[2018-10-22T15:46:34Z] Deleting existing primary...
ERRO[2018-10-22T15:46:34Z] pods is forbidden: User "system:serviceaccount:default:pg-watcher" cannot deletecollection pods in the namespace "default"
ERRO[2018-10-22T15:46:34Z] An error occurred while deleting the old primary
INFO[2018-10-22T15:46:34Z] Deleted old primary
INFO[2018-10-22T15:46:34Z] Choosing failover replica...
ERRO[2018-10-22T15:46:34Z] Error getting pods command
INFO[2018-10-22T15:46:34Z] Chose failover target ()
INFO[2018-10-22T15:46:34Z] Promoting failover replica...
ERRO[2018-10-22T15:46:34Z] An error occurred while promoting the failover replica
ERRO[2018-10-22T15:46:34Z] Failover process failed: could not get pod info: resource name may not be empty
INFO[2018-10-22T15:46:34Z] Executing post-hook: /hooks/watch-post-hook
INFO[2018-10-22T15:46:44Z] Health Checking: 'crunchy-primary'
ERRO[2018-10-22T15:46:54Z] dial tcp 10.105.143.178:5432: i/o timeout

I am using kubernetes 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by uhaani** [comment]
Please provide the docker file for crunchy-watch and if its possible we can contribute to crunchy-watcher and fix these issues?

**Comment by uhaani** [comment]
Hi
I tried with crunchy-watch:centos7-10.5-2.1.1

**Comment by davecramer** [comment]
You need to use a different namespace other than default.

**Comment by uhaani** [comment]
Yes, i tried creating with different namespace as well

**Comment by davecramer** [comment]
Well it's somewhat obvious that we have 2 different environments. Did you follow https://crunchydata.github.io/crunchy-containers/stable/installation/environment-setup/ and setup the environment variables as suggested ?

**Comment by uhaani** [comment]
I have set the environment variables as below 
export CCP_BASEOS=centos7
export CCP_PGVERSION=10
export CCP_PG_FULLVERSION=10.5
export CCP_VERSION=2.1.1
export CCP_IMAGE_PREFIX=crunchydata
export CCP_CLI=kubectl
export CCP_NAMESPACE=test

when primary is killed , i see the replica label getting changed. But it doesn't start as primary

[root crunchy-database] #kubectl describe pods crunchy-replica-0 -n test
Name:               crunchy-replica-0
Namespace:          test
Priority:           0
PriorityClassName:  <none>
Labels:          app=crunchy-replica
                    controller-revision-hash=crunchy-replica-76f888bb4
                    name=crunchy-primary
                    replicatype=trigger
                    statefulset.kubernetes.io/pod-name=crunchy-replica-0
Annotations:        <none>
Status:             Running

Below are the crunchy-watch logs :
[root crunchy-database]#kubectl logs watch -n test
Starting crunchy watch
Started...
INFO[2018-11-15T07:00:29Z] Loading Platform Module: kube
INFO[2018-11-15T07:00:29Z] Waiting for signal...
INFO[2018-11-15T07:00:29Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:00:29Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:00:39Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:00:39Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:00:49Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:00:49Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:00:59Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:00:59Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:09Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:01:09Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:19Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:01:19Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:29Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:01:29Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:39Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:01:39Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:49Z] Health Checking: 'crunchy-primary'
INFO[2018-11-15T07:01:49Z] Successfully reached 'crunchy-primary'
INFO[2018-11-15T07:01:59Z] Health Checking: 'crunchy-primary'
ERRO[2018-11-15T07:02:09Z] dial tcp 10.103.127.185:5432: i/o timeout
ERRO[2018-11-15T07:02:09Z] Could not reach 'crunchy-primary' (Attempt: 1)
INFO[2018-11-15T07:02:09Z] Executing pre-hook: /hooks/watch-pre-hook
INFO[2018-11-15T07:02:09Z] Processing Failover: Strategy - latest
INFO[2018-11-15T07:02:09Z] Deleting existing primary...
INFO[2018-11-15T07:02:09Z] Deleted old primary
INFO[2018-11-15T07:02:09Z] Choosing failover replica...
INFO[2018-11-15T07:02:09Z] Chose failover target (crunchy-replica-0)
INFO[2018-11-15T07:02:09Z] Promoting failover replica...
DEBU[2018-11-15T07:02:09Z] executing cmd: [/opt/cpm/bin/promote.sh] on pod crunchy-replica-0 in namespace test container: postgres
INFO[2018-11-15T07:02:09Z] Relabeling failover replica...
DEBU[2018-11-15T07:02:09Z] label: statefulset.kubernetes.io/pod-name
DEBU[2018-11-15T07:02:09Z] label: app
DEBU[2018-11-15T07:02:09Z] label: controller-revision-hash
DEBU[2018-11-15T07:02:09Z] label: name
DEBU[2018-11-15T07:02:09Z] label: replicatype
INFO[2018-11-15T07:02:09Z] Executing post-hook: /hooks/watch-post-hook
INFO[2018-11-15T07:02:19Z] Health Checking: 'crunchy-primary'
ERRO[2018-11-15T07:02:29Z] dial tcp 10.103.127.185:5432: i/o timeout
ERRO[2018-11-15T07:02:29Z] Could not reach 'crunchy-primary' (Attempt: 1)
INFO[2018-11-15T07:02:39Z] Health Checking: 'crunchy-primary'
ERRO[2018-11-15T07:02:49Z] dial tcp 10.103.127.185:5432: i/o timeout
ERRO[2018-11-15T07:02:49Z] Could not reach 'crunchy-primary' (Attempt: 1)

Let me know if you need any more information.

**Comment by GajaHebbar** [comment]
@davecramer 
I have used the image centos7-11.1-2.2.0 132 MB
Last update: a month ago
Getting same error. 
@cahoonpwork  had mentioned to use tag "2.2.0-rc6" which is not available https://hub.docker.com/r/crunchydata/crunchy-watch/tags/

INFO[2019-01-09T10:24:04Z] Successfully reached 'primary-metrics'
INFO[2019-01-09T10:24:14Z] Health Checking: 'primary-metrics'
INFO[2019-01-09T10:24:14Z] Successfully reached 'primary-metrics'
INFO[2019-01-09T10:24:24Z] Health Checking: 'primary-metrics'
INFO[2019-01-09T10:24:24Z] Successfully reached 'primary-metrics'
INFO[2019-01-09T10:24:34Z] Health Checking: 'primary-metrics'
ERRO[2019-01-09T10:24:44Z] dial tcp 10.108.3.69:5432: i/o timeout
ERRO[2019-01-09T10:24:44Z] Could not reach 'primary-metrics' (Attempt: 1)
INFO[2019-01-09T10:24:44Z] Executing pre-hook: /hooks/watch-pre-hook
INFO[2019-01-09T10:24:44Z] Processing Failover: Strategy - latest
INFO[2019-01-09T10:24:44Z] Deleting existing primary...
ERRO[2019-01-09T10:24:44Z] pods is forbidden: User "system:serviceaccount:gaja:pg-watcher" cannot deletecollection pods in the namespace "gaja"
ERRO[2019-01-09T10:24:44Z] An error occurred while deleting the old primary
INFO[2019-01-09T10:24:44Z] Deleted old primary
INFO[2019-01-09T10:24:44Z] Choosing failover replica...
ERRO[2019-01-09T10:24:44Z] Error getting pods command
INFO[2019-01-09T10:24:44Z] Chose failover target ()
INFO[2019-01-09T10:24:44Z] Promoting failover replica...
ERRO[2019-01-09T10:24:44Z] Cannot promote replica:
ERRO[2019-01-09T10:24:44Z] Failover process failed: could not get pod info: resource name may not be empty
INFO[2019-01-09T10:24:44Z] Executing post-hook: /hooks/watch-post-hook
INFO[2019-01-09T10:24:54Z] Health Checking: 'primary-metrics'
ERRO[2019-01-09T10:25:04Z] dial tcp 10.108.3.69:5432: i/o timeout
ERRO[2019-01-09T10:25:04Z] Could not reach 'primary-metrics' (Attempt: 1)
INFO[2019-01-09T10:25:14Z] Health Checking: 'primary-metrics'

Please advise, Its bit critical for us to get this thing working.
Its been 3 months now and we are unable to find the solution. Appreciate your help.

**Comment by jmccormick2001** [comment]
ERRO[2019-01-09T10:24:44Z] pods is forbidden: User "system:serviceaccount:gaja:pg-watcher" cannot deletecollection pods in the namespace "gaja"

that suggests an RBAC error, verify your RBAC settings are correct for this user/namespace.

FYI, we have decided to deprecate crunchy-watch going forward.  Our focus is on doing HA within the Postgres Operator going forward.

regards.
